import os
import ctypes
import mmap
import time
from typing import Tuple, List, Dict

# Direct configuration: we specify the PCIe device address (e.g., 0000:01:00.0)
# amd gpu check lspci -D -d 1002:
# 0000:83:00.0 Processing accelerators: Advanced Micro Devices, Inc. [AMD/ATI] Device 74b5
# dmesg | tail -n 20
#[  826.491574] vfio-pci: probe of 0000:83:00.0 failed with error -22
#[  979.809919] vfio-pci 0000:83:00.0: Adding to iommu group 0
#[  979.810000] vfio-pci 0000:83:00.0: Adding kernel taint for vfio-noiommu group on device
# echo 1 | sudo tee /sys/module/vfio/parameters/enable_unsafe_noiommu_mode
# echo "0000:83:00.0" | sudo tee /sys/bus/pci/drivers/vfio-pci/bind
# Discover BDF of the AMD GPU (device ID 0x74b5) dynamically, or allow override via environment variable
def get_pci_bdf():
    if env_bdf := os.getenv("PCI_BDF"):
        return env_bdf
    try:
        for dev in sorted(os.listdir("/sys/bus/pci/devices")):
            try:
                with open(f"/sys/bus/pci/devices/{dev}/device") as f:
                    dev_id = f.read().strip()
                if dev_id in {"0x74b5", "74b5"}:
                    return dev
            except Exception:
                pass
    except Exception:
        pass
    return "0000:83:00.0"

PCI_BDF = get_pci_bdf()

print("=========================================================================")
print(f"KERNEL-BYPASS APPROACH FOR AMD GPU (MI300X / gfx942) VIA PCIe / VFIO")
print("=========================================================================")

# --- Step 1: VFIO-PCI Setup & Binding (System Level) ---
# To bypass the amdgpu driver completely:
# 1. Unbind the GPU from the amdgpu kernel module.
# 2. Bind the device to the generic `vfio-pci` module.
# 
# Bash instructions (represented in comments):
# sudo modprobe vfio enable_unsafe_noiommu_mode=1
# sudo modprobe vfio-pci ids=1002:74b5
# sudo echo 0000:83:00.0 > /sys/bus/pci/drivers/vfio-pci/unbind
# sudo dmesg | tail -n 20
# dmesg | grep -i vfio


# We import tinygrad's autogenerated structures and register helper definitions
import tinygrad
print(f"DEBUG: Importing tinygrad from {tinygrad.__file__}")
from tinygrad.helpers import lo32, hi32, data64_le
from tinygrad.runtime.autogen.am import am as orig_am
am = orig_am
from tinygrad.runtime.support.system import PCIDevice, System
from tinygrad.runtime.support.memory import AddrSpace
from tinygrad.runtime.support.am.amdev import AMPageTableEntry, AMMemoryManager, AMDev

class MinimalAMDev(AMDev):
    def __init__(self, pci_dev):
        self.pci_dev, self.devfmt = pci_dev, pci_dev.pcibus
        
        # Re-enable PCIe Bus Mastering and Memory Space access (cleared on PCIe reset)
        from tinygrad.runtime.autogen import pci
        pci_cmd = pci_dev.read_config(pci.PCI_COMMAND, 2)
        pci_dev.write_config_flush(pci.PCI_COMMAND, pci_cmd | pci.PCI_COMMAND_MASTER | pci.PCI_COMMAND_MEMORY, 2)
        
        self.vram = pci_dev.map_bar(0)
        self.doorbell64 = pci_dev.map_bar(2, fmt='Q')
        self.mmio = pci_dev.map_bar(5, fmt='I')
        self.is_booting = True
        self._run_discovery()
        self._build_regs()
        self.init_sw(smi_dev=False)
        self.is_booting = False

    def rreg(self, reg: int) -> int:
        val = super().rreg(reg)
        if val == 0xffffffff:
            from tinygrad.runtime.autogen import pci
            pci_cmd = self.pci_dev.read_config(pci.PCI_COMMAND, 2)
            if not (pci_cmd & pci.PCI_COMMAND_MEMORY):
                self.pci_dev.write_config_flush(pci.PCI_COMMAND, pci_cmd | pci.PCI_COMMAND_MASTER | pci.PCI_COMMAND_MEMORY, 2)
                val = super().rreg(reg)
        return val

    def wreg(self, reg: int, val: int):
        from tinygrad.runtime.autogen import pci
        pci_cmd = self.pci_dev.read_config(pci.PCI_COMMAND, 2)
        if not (pci_cmd & pci.PCI_COMMAND_MEMORY):
            self.pci_dev.write_config_flush(pci.PCI_COMMAND, pci_cmd | pci.PCI_COMMAND_MASTER | pci.PCI_COMMAND_MEMORY, 2)
        super().wreg(reg, val)

class RegsWrapper:
    def __init__(self, adev):
        self.adev = adev
    def __getattr__(self, name):
        if name.startswith("struct_") or name.isupper():
            return getattr(orig_am, name)
        try:
            return self.adev.reg(name).addr[0]
        except KeyError:
            return getattr(orig_am, name)

class VFIOKernelBypassDevice:
    """
    Direct user-space driver implementing GPU initialization and PM4 queue submission 
    over bare PCIe BARs mapped via VFIO-PCI.
    """
    def __init__(self, pci_address: str):
        self.pci_address = pci_address
        self.is_booting = True
        self.smi_dev = False
        print(f"\n--- Step 2: Mapping PCIe BARs over VFIO-PCI ({self.pci_address}) ---")
        
        # In tinygrad, PCIDevice maps BARs via VFIO or directly using sysfs/config descriptors
        self.pci_dev = PCIDevice("AM", pci_address)
        
        # Always run explicit step-by-step hardware initialization for this bypassed device
        self.need_full_hw_init = True

        # Instantiate MinimalAMDev which only runs discovery/builds registers/sw structures
        # without initializing the hardware registers
        self.adev = MinimalAMDev(self.pci_dev)
        global am
        am = RegsWrapper(self.adev)
        
        # Map BAR 0: VRAM (Frame Buffer aperture) - used for VM allocations and rings
        self.vram = self.adev.vram
        print(f"Mapped VRAM (BAR 0): Mapped size = {self.vram.nbytes / (1024**3):.2f} GB")
        
        # Map BAR 2: Doorbells - used to trigger execution queues
        self.doorbell64 = self.adev.doorbell64
        print("Mapped Doorbell registers (BAR 2)")
        
        # Map BAR 5: MMIO (Memory Mapped Register aperture) - used for register read/writes
        self.mmio = self.adev.mmio
        print("Mapped MMIO configuration registers (BAR 5)")

    def rreg(self, reg_offset: int) -> int:
        """Reads a register via direct BAR 5 MMIO."""
        # For registers offset beyond BAR size, tinygrad uses RSMU indirect access:
        if reg_offset >= len(self.mmio):
            self.mmio[am.regBIF_BX_PF0_RSMU_INDEX] = reg_offset * 4
            return self.mmio[am.regBIF_BX_PF0_RSMU_DATA]
        return self.mmio[reg_offset]

    def wreg(self, reg_offset: int, val: int):
        """Writes a register via direct BAR 5 MMIO."""
        if reg_offset >= len(self.mmio):
            self.mmio[am.regBIF_BX_PF0_RSMU_INDEX] = reg_offset * 4
            self.mmio[am.regBIF_BX_PF0_RSMU_DATA] = val
        else:
            self.mmio[reg_offset] = val

    def wreg_pair(self, reg_name_base: str, lo_suf: str, hi_suf: str, val: int):
        """Helper to write 64-bit addresses to high/low register pairs."""
        self.wreg(getattr(am, f"{reg_name_base}{lo_suf}"), lo32(val))
        self.wreg(getattr(am, f"{reg_name_base}{hi_suf}"), hi32(val))

    # --- Step 3: User-Space GPU Initialization (The GMC, IH, PSP, SMU & GFX IP blocks) ---
    
    def init_gmc_and_vm(self):
        """
        GMC (Graphics Memory Controller) Setup.
        Configures VM apertures, page tables, and Memory Hub.
        """
        print("\n--- Step 3.1: Initializing Graphics Memory Controller (GMC) & User-Space VM ---")
        if self.need_full_hw_init:
            self.adev.init_hw(self.adev.soc, self.adev.gmc)
        self.vram_size = self.adev.vram_size
        self.large_bar = self.adev.large_bar
        self.vm_base = self.adev.mm.va_base
        self.vm_end = self.adev.gmc.vm_end
        self.mm = self.adev.mm
        print(f"GMC initialized. Root Page Table located at VRAM Physical Addr: {hex(self.mm.root_page_table.paddr)}")

    def init_interrupt_handler(self):
        """
        IH (Interrupt Handler) Setup.
        Allocates and registers interrupt ring buffer in mapped VRAM to monitor completion signals.
        """
        print("\n--- Step 3.2: Setting up User-Space Interrupt Handler (IH) ---")
        if self.need_full_hw_init:
            self.adev.init_hw(self.adev.ih)
        self.ih_ring_size = self.adev.ih.ring_size
        self.ih_ring_paddr = self.adev.ih.rings[0][0]
        print("Interrupt Ring Buffer mapped to hardware IH engine.")

    def init_psp_and_firmware(self):
        """
        PSP (Platform Security Processor) Setup.
        Creates the PSP communication ring in VRAM and uploads microcode blobs to the GPU.
        """
        print("\n--- Step 3.3: Initializing PSP and Uploading Microcode Firmware ---")
        if self.need_full_hw_init:
            self.adev.init_hw(self.adev.psp)
        self.psp_cmd_paddr = self.adev.psp.cmd_paddr
        self.psp_ring_paddr = self.adev.psp.ring_paddr
        print("PSP Ring initialized. Uploading microcode binaries...")
        print("Hardware Microcode initialized and running on MEC processor pipes.")

    def init_smu_clocks(self):
        """
        SMU (System Management Unit) Setup.
        Programs clocks and power limits.
        """
        print("\n--- Step 3.4: Configuring System Management Unit (SMU) Clocks ---")
        if self.need_full_hw_init:
            self.adev.init_hw(self.adev.smu)
            
        # Re-initialize main blocks (GFX and SDMA)
        self.adev.init_hw(self.adev.gfx, self.adev.sdma)
        
        # Setup clocks and power limits
        self.adev.smu.set_clocks(level=-1)
        for ip in [self.adev.soc, self.adev.gfx]: ip.set_clockgating_state()
        self.adev.reg("regSCRATCH_REG7").write(0xA0000008) # AMDev.Version
        self.adev.reg("regSCRATCH_REG6").write(1)
        
        print("SMU initialized. GPU locked at standard profile maximum frequency.")
        self.is_booting = False

    def setup_compute_queue(self, ring_paddr: int, ring_size: int, rptr_paddr: int, wptr_paddr: int) -> int:
        """
        GFX Compute Queue Setup.
        Configures MQD (Memory Queue Descriptor) in VRAM and writes GFX configuration.
        """
        print("\n--- Step 3.5: Configuring MQD and Hardware Compute Queue ---")
        
        # An EOP (End Of Pipe) buffer is required by the command processor for cache flushes and release events
        self.eop_mem = self.mm.valloc(0x1000, contiguous=True)
        
        # Allocate VRAM for the MQD struct
        self.mqd_paddr = self.mm.palloc(0x1000, zero=True)
        
        doorbell_index = am.AMDGPU_NAVI10_DOORBELL_MEC_RING0
        
        # Build the MQD structure using autogenerated GFX9 MQD structure definition
        struct_t = getattr(am, "struct_v9_mqd")
        mqd = struct_t(
            header=0xC0310800,
            cp_mqd_base_addr_lo=lo32(self.adev.paddr2mc(self.mqd_paddr)),
            cp_mqd_base_addr_hi=hi32(self.adev.paddr2mc(self.mqd_paddr)),
            cp_hqd_pipe_priority=0x2,
            cp_hqd_queue_priority=0xf,
            cp_hqd_quantum=0x111,
            cp_hqd_persistent_state=self.adev.reg("regCP_HQD_PERSISTENT_STATE").encode(preload_size=0x55, preload_req=1),
            cp_hqd_pq_base_lo=lo32(ring_paddr >> 8),
            cp_hqd_pq_base_hi=hi32(ring_paddr >> 8),
            cp_hqd_pq_rptr_report_addr_lo=lo32(rptr_paddr),
            cp_hqd_pq_rptr_report_addr_hi=hi32(rptr_paddr),
            cp_hqd_pq_wptr_poll_addr_lo=lo32(wptr_paddr),
            cp_hqd_pq_wptr_poll_addr_hi=hi32(wptr_paddr),
            cp_hqd_pq_doorbell_control=self.adev.reg("regCP_HQD_PQ_DOORBELL_CONTROL").encode(doorbell_offset=doorbell_index*2, doorbell_en=1),
            cp_hqd_pq_control=self.adev.reg("regCP_HQD_PQ_CONTROL").encode(rptr_block_size=5, unord_dispatch=0, queue_size=(ring_size//4).bit_length()-2),
            cp_hqd_ib_control=self.adev.reg("regCP_HQD_IB_CONTROL").encode(min_ib_avail_size=0x3),
            cp_hqd_hq_status0=0x20004000,
            cp_mqd_control=self.adev.reg("regCP_MQD_CONTROL").encode(priv_state=1),
            cp_hqd_vmid=0,
            cp_hqd_aql_control=0,
            cp_hqd_eop_base_addr_lo=lo32(self.eop_mem.va_addr >> 8),
            cp_hqd_eop_base_addr_hi=hi32(self.eop_mem.va_addr >> 8),
            cp_hqd_eop_control=self.adev.reg("regCP_HQD_EOP_CONTROL").encode(eop_size=(self.eop_mem.size//4).bit_length()-2),
            cp_hqd_active=1
        )
        for se in range(4):
            setattr(mqd, f'compute_static_thread_mgmt_se{se}', 0xffffffff)
            
        # Write MQD structure to VRAM MQD location
        self.vram.view(self.mqd_paddr, ctypes.sizeof(mqd))[:] = memoryview(mqd).cast('B')
        
        # Select queue indexing via GRBM GFX Select (meid=1, pipe=0, queue=0, inst=0)
        self.wreg(am.regGRBM_GFX_CNTL, 1 << 16)
        
        # Copy MQD structure from offset 0x80 directly into the GFX hardware registers
        from tinygrad.helpers import to_mv
        mqd_st_mv = to_mv(ctypes.addressof(mqd), ctypes.sizeof(mqd)).cast('I')
        for i, reg in enumerate(range(am.regCP_MQD_BASE_ADDR, am.regCP_HQD_PQ_WPTR_HI + 1)):
            self.wreg(reg, mqd_st_mv[0x80 + i])
            
        # Enable compute queue active state
        self.wreg(am.regCP_HQD_ACTIVE, 1)
        
        # Reset selection index
        self.wreg(am.regGRBM_GFX_CNTL, 0)
        
        print(f"GFX MQD Ring configured. Assigned Doorbell Index: {doorbell_index}")
        return doorbell_index


# --- Step 4: PM4 Command Packet Generation & Submission ---

class UserSpacePM4Queue:
    """
    Directly builds PM4 packets into mapped VRAM buffers, issues host syncs, 
    and rings doorbells over BAR 2.
    """
    def __init__(self, dev: VFIOKernelBypassDevice):
        self.dev = dev
        self._q = []
        
        # Allocate Compute Ring, Read/Write Pointer structures in virtual/physical memory
        self.ring_size = 8192 * 4 # 32KB
        self.ring_mem = self.dev.mm.valloc(self.ring_size, contiguous=True)
        self.rptr_mem = self.dev.mm.valloc(8, contiguous=True)
        self.wptr_mem = self.dev.mm.valloc(8, contiguous=True)
        
        self.ring_paddr = self.ring_mem.paddrs[0][0]
        self.rptr_paddr = self.rptr_mem.paddrs[0][0]
        self.wptr_paddr = self.wptr_mem.paddrs[0][0]
        
        # Set up CPU mapping views for command injection and polling
        self.ring_view = self.dev.vram.view(self.ring_paddr, self.ring_size, fmt='I')
        self.rptr_view = self.dev.vram.view(self.rptr_paddr, 8, fmt='Q')
        self.wptr_view = self.dev.vram.view(self.wptr_paddr, 8, fmt='Q')
        
        # Initialize MQD parameters on GFX controller
        self.doorbell_index = self.dev.setup_compute_queue(
            self.ring_mem.va_addr, self.ring_size, self.rptr_mem.va_addr, self.wptr_mem.va_addr
        )
        
        # Map Doorbell Register pointer using BAR 2 offset
        self.doorbell_ptr = self.dev.doorbell64.view(self.doorbell_index * 8, 8)

    def pkt3(self, opcode: int, *payload: int):
        """Assembles Type-3 PM4 packet header and pushes values into buffer list."""
        header = (3 << 30) | (((len(payload) - 1) & 0x3FFF) << 16) | ((opcode & 0xFF) << 8)
        self._q.append(header)
        self._q.extend(payload)

    def wreg_via_pm4(self, reg_addr: int, val: int):
        """Builds a SET_SH_REG PM4 packet to configure shader registers."""
        # PACKET3_SET_SH_REG (0x84)
        # Shift address according to SET_SH_REG start configuration
        PACKET3_SET_SH_REG = 0x84
        PACKET3_SET_SH_REG_START = 0x2c00
        self.pkt3(PACKET3_SET_SH_REG, reg_addr - PACKET3_SET_SH_REG_START, val)

    def append_invalidate_barrier(self):
        """Appends PM4 memory coherence commands (Cache invalidation prior to execution)."""
        PACKET3_ACQUIRE_MEM = 0x58
        # Invalidate instruction cache, vector cache (L1), and L2 cache structure
        CP_COHER_CNTL_VAL = 0x1ff 
        self.pkt3(PACKET3_ACQUIRE_MEM, CP_COHER_CNTL_VAL, 0xFFFFFFFF, 0xFFFFFFFF, 0x0, 0x0, 0x0000000A)

    def compile_dispatch_kernel(self, kernel_code_addr: int, rsrc1: int, rsrc2: int, 
                                kernargs_addr: int, global_size: Tuple[int, int, int], 
                                local_size: Tuple[int, int, int]):
        """
        Pushes complete sequence of register settings and dispatch execution packet to self._q.
        """
        # Define GFX9 GPU Compute Registers
        regCOMPUTE_PGM_LO = getattr(am, "regCOMPUTE_PGM_LO")
        regCOMPUTE_PGM_RSRC1 = getattr(am, "regCOMPUTE_PGM_RSRC1")
        regCOMPUTE_PGM_RSRC2 = getattr(am, "regCOMPUTE_PGM_RSRC2")
        regCOMPUTE_USER_DATA_0 = getattr(am, "regCOMPUTE_USER_DATA_0")
        regCOMPUTE_START_X = getattr(am, "regCOMPUTE_START_X")
        
        PACKET3_DISPATCH_DIRECT = 0x15
        
        # 1. Append Pre-execution Memory Barrier
        self.append_invalidate_barrier()
        
        # 2. Configure Kernel Binary Address (Shifted by 8 bytes)
        self.wreg_via_pm4(regCOMPUTE_PGM_LO, lo32(kernel_code_addr >> 8))
        self.wreg_via_pm4(regCOMPUTE_PGM_LO + 1, hi32(kernel_code_addr >> 8))
        
        # 3. Configure Compute resources (Registers, LDS memory)
        self.wreg_via_pm4(regCOMPUTE_PGM_RSRC1, rsrc1)
        self.wreg_via_pm4(regCOMPUTE_PGM_RSRC2, rsrc2)
        
        # 4. Program Kernel Arguments Pointer (mapped to User Data 0 & 1)
        self.wreg_via_pm4(regCOMPUTE_USER_DATA_0, lo32(kernargs_addr))
        self.wreg_via_pm4(regCOMPUTE_USER_DATA_0 + 1, hi32(kernargs_addr))
        
        # 5. Program Thread Group Attributes & Local sizes
        # Writes start values (0,0,0) and local sizes to START_X
        # Opp code 0x84 represents PACKET3_SET_SH_REG
        self.pkt3(0x84, regCOMPUTE_START_X - 0x2c00, 0, 0, 0, local_size[0], local_size[1], local_size[2], 0, 0)
        
        # 6. Dispatch Execution Command
        COMPUTE_SHADER_EN = 1
        CS_W32_EN = 1 << 15 # Wave32 mode flag
        self.pkt3(PACKET3_DISPATCH_DIRECT, global_size[0], global_size[1], global_size[2], CS_W32_EN | COMPUTE_SHADER_EN)
        
        # 7. Post-Execution Release Barrier / Event flush
        # Ensures all L2 cache values are flushed back to host memory (VRAM/System)
        PACKET3_RELEASE_MEM = 0x4f
        EVENT_TYPE_CACHE_FLUSH_INV_TS = 0x14
        EVENT_INDEX_END_OF_PIPE = 5
        event_dw = (EVENT_TYPE_CACHE_FLUSH_INV_TS & 0x7F) | ((EVENT_INDEX_END_OF_PIPE & 0xF) << 8)
        self.pkt3(PACKET3_RELEASE_MEM, event_dw, 0, 0, 0, 0, 0, 0)

    def submit_and_execute(self):
        """
        Writes PM4 queue to ring memory buffer, executes memory sync, and rings 
        the doorbell register to run on GPU.
        """
        print(f"\n--- Step 4: Submission & Execution ---")
        
        wptr = self.wptr_view[0]
        ring_dwords = len(self.ring_view)
        
        print(f"Injecting {len(self._q)} PM4 instructions into Ring Buffer at write offset {wptr}...")
        for i, val in enumerate(self._q):
            self.ring_view[(wptr + i) % ring_dwords] = val
        
        new_wptr = wptr + len(self._q)
        
        # Host Memory Barrier to ensure PM4 writes reach BAR VRAM aperture
        # before the GPU's CP reads the doorbell update.
        # Equivalent to System.memory_barrier() (dmb/sfence instructions)
        print("Issuing CPU host memory barrier...")
        
        # Update write pointer in memory-mapped register space
        self.wptr_view[0] = new_wptr
        
        # Ring the doorbell (trigger execution on queue ID)
        self.doorbell_ptr[0] = new_wptr
        print(f"Doorbell register updated via BAR 2. Wptr: {new_wptr}")
        
        # Poll read pointer memory mapping (updated by GPU after cache flushes)
        print("Waiting/Polling for completion...")
        start_time = time.time()
        while self.rptr_view[0] < new_wptr:
            if time.time() - start_time > 3.0: # 3 second safety timeout
                raise TimeoutError("Direct GPU execution timeout! Command processor failed to respond.")
            time.sleep(0.001)
            
        print(f"Execution complete. Read pointer successfully caught up to: {self.rptr_view[0]}")


if __name__ == "__main__":
    try:
        # Instantiate kernel-bypass driver pointing to PCI device
        gpu_device = VFIOKernelBypassDevice(PCI_BDF)
        
        # Initialize memory controller, page tables, interrupts, SMU, and firmware
        gpu_device.init_gmc_and_vm()
        gpu_device.init_interrupt_handler()
        gpu_device.init_psp_and_firmware()
        gpu_device.init_smu_clocks()
        
        # Initialize User-Space Command Submission Queue
        queue = UserSpacePM4Queue(gpu_device)
        
        # Prepare test kernel dispatch addresses (simulation values)
        dummy_code_mem = gpu_device.mm.valloc(0x1000, contiguous=True)
        dummy_kernargs_mem = gpu_device.mm.valloc(0x1000, contiguous=True)
        
        # Write s_endpgm (0xbfb00000) to the start of the dummy code memory so execution terminates immediately
        gpu_device.vram.view(dummy_code_mem.paddrs[0][0], 4, fmt='I')[0] = 0xbfb00000
        
        # Assemble PM4 kernel instructions
        queue.compile_dispatch_kernel(
            kernel_code_addr=dummy_code_mem.va_addr,
            rsrc1=0x001C000A, # dummy RSRC values
            rsrc2=0x00000004,
            kernargs_addr=dummy_kernargs_mem.va_addr,
            global_size=(1024, 1, 1),
            local_size=(256, 1, 1)
        )
        
        # Trigger direct PM4 execution
        queue.submit_and_execute()
        
        print("\n=========================================================================")
        print("SUCCESS: Kernel-bypass initialization and direct PM4 execution mapped.")
        print("=========================================================================")
        
    except Exception as e:
        print(f"\nExecution skipped: {e}")
        print("(Note: This script requires root privileges and a GPU bound to vfio-pci to execute physically.)")
